### DISCUSSION TITLE
Mongock Transaction

### DISCUSSION THREAD

**Discussion by akanzari** [flamingock/mongock#35] [Q&A] [answered]
I have an application spring boot and spring data, i tried to use mongock and i configure it like below

```
mongock:
  migration-scan-package:
    - com.digital.ecom.config.dbmigrations
  transaction-enabled: true
```

but when i run the application i have this error

`Caused by: com.mongodb.MongoCommandException: Command failed with error 20 (IllegalOperation): 'Transaction numbers are only allowed on a replica set member or mongos' on server 127.0.0.1:27017. The full response is {"ok": 0.0, "errmsg": "Transaction numbers are only allowed on a replica set member or mongos", "code": 20, "codeName": "IllegalOperation"}
`
spring boot: 2.7.1
mongock: 5.1.3
